CONFIGDIR: .
VARDIR: ./var/manuheart
LOGFILE: ./var/manuheart.log
LOGLEVEL: 3
CHECKPERIOD: 3
RUNMODE: once
GROUPFILE: _CONFIGDIR_/groups
HOSTFILE: _CONFIGDIR_/hosts
HOSTSTATUSOUTFILE: ./var/manuheart/status/hoststatus
GROUPSTATUSOUTFILE: ./var/manuheart/status/groupstatus
SYSSTATUSOUTFILE: ./var/manuheart/status/sysstatus
